- :first_name: "Jeff"
  :last_name: "Goldblum"
- :first_name: "Seth"
  :last_name: "Brundle"
- :first_name: "Ian"
  :last_name: "Malcolm"
- :first_name: "David"
  :last_name: "Levinson"
- :first_name: "Verminous"
  :last_name: "Skumm"
- :first_name: "Alistair"
  :last_name: "Hennessey"
- :first_name: "Chef"
  :last_name: "Goldblum"
- :first_name: "En Dwi"
  :last_name: "Gast"
- :first_name: "The"
  :last_name: "Grandmaster"
